# Generated by Django 5.2.5 on 2025-12-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_userprofile_address_userprofile_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('Italian', 'Italian'), ('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Japanese', 'Japanese'), ('Fast Food', 'Fast Food'), ('American', 'American'), ('Mexican', 'Mexican'), ('Healthy', 'Healthy'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
